package main

const header = `package cu

// #include <cuda.h>
import "C"

// This file was generated by the genlib program. DO NOT EDIT


`

const resultHeader = `package cu

//#include <cuda.h>
import "C"
import "fmt"

// This file was generated by the genlib program. DO NOT EDIT

// cuResult is the Go version of CUresult:
// http://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1gc6c391505e117393cc2558fff6bfc2e9
type cuResult int

func (err cuResult) Error() string  { return err.String() }
func (err cuResult) String() string {
    if msg, ok := resString[err]; ok {
        return msg
    }
    return fmt.Sprintf("UnknownErrorCode:%d", err)
}

func result(x C.CUresult) error {
	err := cuResult(x)
	if err == Success {
		return nil
	}
	return err
}

`
