package cudnn

/* Generated by gencudnn. DO NOT EDIT */

// #include <cudnn_v7.h>
import "C"
import "github.com/pkg/errors"

// Pooling is a representation of cudnnPoolingDescriptor_t.
type Pooling struct {
	internal C.cudnnPoolingDescriptor_t

	//TODO
}

// NewPooling creates a new Pooling.
func NewPooling(mode PoolingMode, maxpoolingNanOpt NanPropagation, windowHeight int, windowWidth int, verticalPadding int, horizontalPadding int, verticalStride int, horizontalStride int) (retVal *Pooling, err error) {
	// available "Set" methods:
	//	cudnnSetPooling2dDescriptor
	//	cudnnSetPoolingNdDescriptor
	return nil, errors.Errorf("TODO: Manual Intervention required")
}

// TODO: Getters for Pooling

func destroyPooling(obj *Pooling) { C.cudnnDestroyPoolingDescriptor(obj.internal) }
