package cudnn

/* WAS Generated by gencudnn. DO NOT EDIT */

// #include <cudnn.h>
import "C"
import (
	"runtime"
	"unsafe"
)

// FusedOpVariantParams is a representation of cudnnFusedOpsVariantParamPack_t.
type FusedOpVariantParams struct {
	internal C.cudnnFusedOpsVariantParamPack_t

	ops        FusedOps
	paramLabel FusedOpsVariantParamLabel
	ptr        Memory
}

// NewFusedOpVariantParams creates a new FusedOpVariantParams.
func NewFusedOpVariantParams(ops FusedOps, paramLabel FusedOpsVariantParamLabel, ptr Memory) (retVal *FusedOpVariantParams, err error) {
	var internal C.cudnnFusedOpsVariantParamPack_t
	if err := result(C.cudnnCreateFusedOpsVariantParamPack(&internal, ops.C())); err != nil {
		return nil, err
	}

	if err := result(C.cudnnSetFusedOpsVariantParamPackAttribute(internal, paramLabel.C(), unsafe.Pointer(ptr.Uintptr()))); err != nil {
		return nil, err
	}

	retVal = &FusedOpVariantParams{
		internal:   internal,
		paramLabel: paramLabel,
		ptr:        ptr,
		ops:        ops,
	}
	runtime.SetFinalizer(retVal, destroyFusedOpVariantParams)
	return retVal, nil
}

// C returns the internal cgo representation.
func (f *FusedOpVariantParams) C() C.cudnnFusedOpsVariantParamPack_t { return f.internal }

// Ops returns the ops that are fused.
func (f *FusedOpVariantParams) Ops() FusedOps { return f.ops }

// ParamLabel returns the internal paramLabel.
func (f *FusedOpVariantParams) ParamLabel() FusedOpsVariantParamLabel { return f.paramLabel }

// Ptr returns the internal ptr.
func (f *FusedOpVariantParams) Ptr() Memory { return f.ptr }

func destroyFusedOpVariantParams(obj *FusedOpVariantParams) {
	C.cudnnDestroyFusedOpsVariantParamPack(obj.internal)
}
